9. Improve your models:
    - Data side: handle outliers, multicollinearity, feature selection, normalization/standardization, feature engineering, etc.
    - Model side: try other models (especially ensemble methods) and perform hyperparameter tuning.
10. Compare all models and select the best one.
11. Identify which features most strongly influence house prices based on your best model.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression

In [2]:
price_data = pd.read_csv("../data/data_final_kingcounty_houses.csv")
price_data.head()

,Unnamed: 0,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,sqft_basement,lat,long,sqft_living15,sqft_lot15,year,month,day,house_age,is_renovated
0,0,7129300520,221900.0,3,1.00,1180,5650,1.0,0,0,...,0,47.5112,-122.257,1340,5650,2014,10,13,60,0
1,1,6414100192,538000.0,3,2.25,2570,7242,2.0,0,0,...,400,47.7210,-122.319,1690,7639,2014,12,9,64,1
2,2,5631500400,180000.0,2,1.00,770,10000,1.0,0,0,...,0,47.7379,-122.233,2720,8062,2015,2,25,82,0
3,3,2487200875,604000.0,4,3.00,1960,5000,1.0,0,0,...,910,47.5208,-122.393,1360,5000,2014,12,9,50,0
4,4,1954400510,510000.0,3,2.00,1680,8080,1.0,0,0,...,0,47.6168,-122.045,1800,7503,2015,2,18,28,0

In [3]:
print(price_data.shape)

(21613, 23)

In [4]:
price_data['price'].value_counts()

price
350000.0     172
450000.0     172
550000.0     159
500000.0     152
425000.0     150
            ...
607010.0       1
1362500.0      1
298800.0       1
957500.0       1
402101.0       1
Name: count, Length: 4028, dtype: int64

In [5]:
pd.cut(price_data['price'],4,labels=['Low','Mid','Average','Top'])

0        Low
1        Low
2        Low
3        Low
4        Low
        ...
21608    Low
21609    Low
21610    Low
21611    Low
21612    Low
Name: price, Length: 21613, dtype: category
Categories (4, object): ['Low' < 'Mid' < 'Average' < 'Top']

In [6]:
TARGET = "price"
X = price_data.drop(columns=[TARGET])
y = price_data[TARGET]

print(price_data.shape)
print(price_data.head())

(21613, 23)
   Unnamed: 0          id     price  bedrooms  bathrooms  sqft_living  \
0           0  7129300520  221900.0         3       1.00         1180
1           1  6414100192  538000.0         3       2.25         2570
2           2  5631500400  180000.0         2       1.00          770
3           3  2487200875  604000.0         4       3.00         1960
4           4  1954400510  510000.0         3       2.00         1680

   sqft_lot  floors  waterfront  view  ...  sqft_basement      lat     long  \
0      5650     1.0           0     0  ...              0  47.5112 -122.257
1      7242     2.0           0     0  ...            400  47.7210 -122.319
2     10000     1.0           0     0  ...              0  47.7379 -122.233
3      5000     1.0           0     0  ...            910  47.5208 -122.393
4      8080     1.0           0     0  ...              0  47.6168 -122.045

   sqft_living15  sqft_lot15  year  month  day  house_age  is_renovated
0           1340        5650  2014     10   13         60             0
1           1690        7639  2014     12    9         64             1
2           2720        8062  2015      2   25         82             0
3           1360        5000  2014     12    9         50             0
4           1800        7503  2015      2   18         28             0

[5 rows x 23 columns]

In [7]:
print(X.head())
print(y.head())
print(X.head().shape)
print(y.head().shape)

   Unnamed: 0          id  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0           0  7129300520         3       1.00         1180      5650     1.0
1           1  6414100192         3       2.25         2570      7242     2.0
2           2  5631500400         2       1.00          770     10000     1.0
3           3  2487200875         4       3.00         1960      5000     1.0
4           4  1954400510         3       2.00         1680      8080     1.0

   waterfront  view  condition  ...  sqft_basement      lat     long  \
0           0     0          3  ...              0  47.5112 -122.257
1           0     0          3  ...            400  47.7210 -122.319
2           0     0          3  ...              0  47.7379 -122.233
3           0     0          5  ...            910  47.5208 -122.393
4           0     0          3  ...              0  47.6168 -122.045

   sqft_living15  sqft_lot15  year  month  day  house_age  is_renovated
0           1340        5650  2014     10   13         60             0
1           1690        7639  2014     12    9         64             1
2           2720        8062  2015      2   25         82             0
3           1360        5000  2014     12    9         50             0
4           1800        7503  2015      2   18         28             0

[5 rows x 22 columns]
0    221900.0
1    538000.0
2    180000.0
3    604000.0
4    510000.0
Name: price, dtype: float64
(5, 22)
(5,)

In [8]:
y.head()

0    221900.0
1    538000.0
2    180000.0
3    604000.0
4    510000.0
Name: price, dtype: float64

In [9]:
reg = LinearRegression()
reg.fit(X, y)
reg.score(X, y)

0.6974237374831864

In [10]:
price_data_transformed = price_data.copy()
X=price_data_transformed.drop(columns=[TARGET])
y=price_data_transformed[TARGET]

In [11]:
reg = LinearRegression()
reg.fit(X, y)
reg.score(X, y)

0.6974237374831864

Randomforest tree

In [12]:
X = price_data.drop('price', axis=1)
y = price_data['price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
from sklearn.ensemble import RandomForestRegressor
rf_regressor = RandomForestRegressor(random_state=1)
rf_regressor.fit(X_train, y_train)

RandomForestRegressor(random_state=1)

In [18]:
y_pred = rf_regressor.predict(X_test)

In [20]:
print("price of the houses:",y_pred)

price of the houses: [ 381819.    888398.11 1093002.73 ...  296415.55  571992.13  335344.97]

In [25]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error: {mse:.2f}")
print(f"R-squared Score: {r2:.2f}")

Mean Squared Error: 21326013116.20
R-squared Score: 0.86

In [26]:
single_data = X_test.iloc[0].values.reshape(1, -1)
predicted_value = rf_regressor.predict(single_data)
print(f"Predicted Value: {predicted_value[0]:.2f}")
print(f"Actual Value: {y_test.iloc[0]:.2f}")

Predicted Value: 381819.00
Actual Value: 365000.00

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

GradientBoosting - Regression

In [31]:
from sklearn.ensemble import GradientBoostingRegressor

gbr = GradientBoostingRegressor(loss='absolute_error',
                                learning_rate=0.1,
                                n_estimators=300,
                                max_depth = 1, 
                                random_state = 23,
                                max_features = 5)

gbr.fit(X_train, y_train)

pred_y = gbr.predict(X_test)

test_rmse = mean_squared_error(y_test, pred_y) ** (1 / 2)

print('Root mean Square error: {:.2f}'.format(test_rmse))

Root mean Square error: 215956.31

XGBoost

In [32]:
from xgboost import XGBRegressor
from sklearn.model_selection import GridSearchCV

In [33]:
xgb = XGBRegressor(random_state=42)

param_grid_higher = {
'n_estimators': [300, 500, 700],
'max_depth': [7, 9, 11],
'learning_rate': [0.01, 0.05],
}
grid_search_higher = GridSearchCV(estimator=xgb, param_grid=param_grid_higher, scoring='neg_mean_squared_error', cv=5, verbose=1)

grid_search_higher.fit(X_train, y_train)
grid_predictions_higher = grid_search_higher.predict(X_test)
# Best parameters and score
print("Best Parameters:", grid_search_higher.best_params_)
print("Best Score:", grid_search_higher.best_score_)

Fitting 5 folds for each of 18 candidates, totalling 90 fits
Best Parameters: {'learning_rate': 0.05, 'max_depth': 7, 'n_estimators': 700}
Best Score: -14362363466.24046

In [ ]:
%pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: xgboost in c:\users\user\appdata\roaming\python\python313\site-packages (3.2.0)
Requirement already satisfied: numpy in c:\users\user\appdata\roaming\python\python313\site-packages (from xgboost) (2.4.4)
Requirement already satisfied: scipy in c:\users\user\appdata\roaming\python\python313\site-packages (from xgboost) (1.17.1)
Note: you may need to restart the kernel to use updated packages.

In [41]:
import xgboost as xgb
xgb_reg = xgb.XGBRegressor()
xgb_reg.fit(X_train, y_train)
y_pred = xgb_reg.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error: {mse:.2f}")
print(f"R-squared Score: {r2:.2f}")

Mean Squared Error: 22202892881.60
R-squared Score: 0.85

In [38]:
y_train_pred = xgb_reg.predict(X_train)

In [48]:
from sklearn.model_selection import GridSearchCV
import xgboost as xgb

# Base model
xgb_reg = xgb.XGBRegressor(random_state=42)

# Parameter grid (like alphas/l1_ratio in ElasticNet)
param_grid = {
    'max_depth': [3, 5, 7, 9], # second
    'learning_rate': [0.01, 0.1, 0.2],  #Third
    'n_estimators': [100, 200]      #Fourth
}

# Grid search with cross-validation
grid_search = GridSearchCV(
    estimator=xgb_reg,
    param_grid=param_grid,
    cv=5,
    scoring='neg_mean_squared_error',
    n_jobs=-1
)

# Fit
grid_search.fit(X_train, y_train)

# Best model
best_xgb = grid_search.best_estimator_

print("Best max_depth:", grid_search.best_params_)

# Predictions
ypred_train_xgb = best_xgb.predict(X_train)
ypred_test_xgb = best_xgb.predict(X_test)

Best max_depth: {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}

In [49]:
# Dataframe with rows Linear Regression, Decision Tree Regressor and XGBoost
# columns: accuracy_train, accuracy_test, MAE_train, MAE_test, R2_train, R2_test

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

def evaluate(y_train, ypred_train, y_test, ypred_test):
    return {
        "MAE_train": mean_absolute_error(y_train, ypred_train),
        "MAE_test": mean_absolute_error(y_test, ypred_test),
        
        "RMSE_train": np.sqrt(mean_squared_error(y_train, ypred_train)),
        "RMSE_test": np.sqrt(mean_squared_error(y_test, ypred_test)),
        
        "R²_train": r2_score(y_train, ypred_train),
        "R²_test": r2_score(y_test, ypred_test),
    }

results = pd.DataFrame({
   
   # "Linear Regression": evaluate(y_train, ypred_train_linreg, y_test, ypred_test_linreg),
   # "Decision Tree": evaluate(y_train, ypred_train_dectree, y_test, ypred_test_dectree),
   # "XGBoost": evaluate(y_train, ypred_train_xgb, y_test, ypred_test_xgb),
    "XGBoost-First":evaluate(y_train, y_train_pred, y_test, y_pred),
    "XGBoost-Second":evaluate(y_train, ypred_train_xgb, y_test, ypred_test_xgb),
    "XGBoost-Third":evaluate(y_train, ypred_train_xgb, y_test, ypred_test_xgb),
    "XGBoost-Fourth":evaluate(y_train, ypred_train_xgb, y_test, ypred_test_xgb)

}).T

results

,MAE_train,MAE_test,RMSE_train,RMSE_test,R²_train,R²_test
XGBoost-First,38358.603269,71645.527921,54417.681590,149006.351816,0.977334,0.853133
XGBoost-Second,50322.330066,69649.908890,74160.503342,138749.773260,0.957904,0.872656
XGBoost-Third,50322.330066,69649.908890,74160.503342,138749.773260,0.957904,0.872656
XGBoost-Fourth,50322.330066,69649.908890,74160.503342,138749.773260,0.957904,0.872656

Need to explore the randomclassifier

In [23]:
from sklearn.ensemble import RandomForestClassifier
forest_model = RandomForestClassifier(random_state=1) #not defining any hyperparameters
forest_model.fit(X_train, y_train)

KeyboardInterrupt:

In [ ]:
forest_model.score(X_test,y_test)

-Grid Search

In [28]:

from sklearn.model_selection import GridSearchCV
n_estimators = [10,100,500]
max_leaf_nodes = [15, 30, 40]
max_depth = [5,10]

In [ ]:
grid = {'n_estimators': n_estimators,
        'max_leaf_nodes': max_leaf_nodes,
        'max_depth': max_depth}

In [ ]:
forest = RandomForestClassifier()
grid_search = GridSearchCV(estimator = forest, param_grid = grid, cv = 3)

In [ ]:
grid_search.fit(X_train, y_train)

In [ ]:
grid_search.best_params_

In [ ]:
grid_search.best_score_

In [ ]:
grid_search.score(X_test, y_test)

In [ ]:
from xgboost import XGBRegressor
from sklearn.model_selection import GridSearchCV

xgb = XGBRegressor(random_state=42)

param_grid_higher = {
'n_estimators': [300, 500, 700],
'max_depth': [7, 9, 11],
'learning_rate': [0.01, 0.05],
#'subsample': [0.6, 0.8],
#'colsample_bytree': [0.6, 0.8]
}
grid_search_higher = GridSearchCV(estimator=xgb, param_grid=param_grid_higher, scoring='neg_mean_squared_error', cv=5, verbose=1)

grid_search_higher.fit(X, y)
grid_predictions_higher = grid_search_higher.predict(X)
# Best parameters and score
print("Best Parameters:", grid_search_higher.best_params_)
print("Best Score:", grid_search_higher.best_score_)
best_model_higher = grid_search_higher.best_estimator_

feature_importance_xgb = pd.Series(best_model.feature_importances_, index=X_log.columns).sort_values(ascending=False)

top_20_features = feature_importance_xgb[:20]
top_features.plot(kind='bar', title="Feature Importance > 0.01", figsize=(10, 6), color='gold')
plt.ylabel("Importance Score")
plt.grid(False)
plt.box(False)
plt.show()

In [ ]:
california_housing = fetch_california_housing()
california_data = pd.DataFrame(california_housing.data, columns=california_housing.feature_names)

In [ ]:
print(california_housing)

In [ ]:
california_housing = fetch_california_housing()
california_data = pd.DataFrame(california_housing.data, columns=california_housing.feature_names)

In [ ]:
california_data = pd.read_csv("../data/data_final_kingcounty_houses.csv")

In [ ]:
california_data['MEDV'] = california_housing.target

X = california_data.drop('MEDV', axis=1)
y = california_data['MEDV']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
%pip install xgboost

In [ ]:
import xgboost as xgb

In [ ]:
xgb.XGBClassifier()

In [ ]:

xgb_reg = xgb.XGBRegressor()
xgb_reg.fit(X_train, y_train)

In [35]:
y_pred = xgb_reg.predict(X_test)

NameError: name 'xgb_reg' is not defined

In [ ]:

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)



print(f"Mean Squared Error: {mse:.2f}")
print(f"R-squared Score: {r2:.2f}")